### ISSUE TITLE
Missing torch import in shuffle_all

### ISSUE THREAD

**Issue by simonamaggio** [rahulvigneswaran/TailCalibX#11]
The current pip release of tailcalib raises `NameError: name 'torch' is not defined` when using `base_engine="pytorch"`. 

Fix:

Add missing import [here](https://github.com/rahulvigneswaran/TailCalibX/blob/b836fd93925efb48f610c08bd56bb0c5a3fca9b0/tailcalib_pip/src/tailcalib.py#LL249C9-L252C46):

```
if self.base_engine == "numpy":
    import numpy as np
    index = np.random.permutation(x.shape[0])
else:
    import torch
    index = torch.randperm(x.size(0))
```

Add missing shuffle condition at lines [here](https://github.com/rahulvigneswaran/TailCalibX/blob/b836fd93925efb48f610c08bd56bb0c5a3fca9b0/tailcalib_pip/src/tailcalib.py#LL135C9-L135C66) and [here](https://github.com/rahulvigneswaran/TailCalibX/blob/b836fd93925efb48f610c08bd56bb0c5a3fca9b0/tailcalib_pip/src/tailcalib.py#L216):

```
if self.shuffle:
    feat_all, labs_all = self.shuffle_all(feat_all, labs_all)
```

**Comment by rahulvigneswaran** [comment]
Hey @simonamaggio, nice catch. Thank you for the fix. Unfortunately, due to the low volume of interest in the pip package, I won't be supporting be updating it. If the interest hikes for this package in future, I will do a release. Till then I will point others to this issue.

I will make sure to avoid such mistakes in my future packages. Thank you!
